//! Generated gRPC protocol bindings
#![allow(clippy::doc_lazy_continuation)]

// This file is generated by running: cargo xtask codegen
// Do not edit this file manually.
include!("generated/android.emulation.control.rs");
