[advisories]
# adb_client depends on the `rsa` crate which is affected by RUSTSEC-2023-0071.
# It looks like this will soon be largely addressed by the `rsa` `0.10` release
# (assuming this is then picked up by `adb_client`)
#
# In practice we only use `adb_client` for connecting to local adb servers that
# interact with locally running emulators, so the risk is minimal, so we can
# afford to wait for the upstream fix and just ignore this advisory in the
# meantime.
#
# Links:
# https://rustsec.org/advisories/RUSTSEC-2023-0071.html
# https://github.com/RustCrypto/RSA/issues/19#issuecomment-1822995643
# https://github.com/RustCrypto/RSA/issues/390
# https://github.com/RustCrypto/RSA/issues/647
ignore = ["RUSTSEC-2023-0071"]
